# 1. Define o Fundo Preto
Window.SetBackgroundTopColor (0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor (0.0, 0.0, 0.0);

# 2. Configurações da Animação (240 frames gerados)
total_frames = 240;
count = 1;

# 3. Carregamento das Imagens (de 1 até 240)
for (i = 1; i <= total_frames; i++) {
   one_piece_image_arr[i] = Image("debian-girl-" + i + ".png");
}

# 4. Posicionamento Centralizado
pos_x = Window.GetWidth()/2 - one_piece_image_arr[1].GetWidth()/2;
pos_y = Window.GetHeight()/2 - one_piece_image_arr[1].GetHeight()/2;

sprite = Sprite(one_piece_image_arr[1]);
sprite.SetX(pos_x);
sprite.SetY(pos_y);

# 5. Função de Atualização (Loop Infinito)
fun refresh_callback () {
   if (count > total_frames) {
     count = 1;
   }

   sprite.SetImage(one_piece_image_arr[count]);
   sprite.SetOpacity(1);
   sprite.SetZ(15);

   count += 1;
}

# 6. Ativa a Animação
Plymouth.SetRefreshFunction (refresh_callback);
